name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check proyect
      uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            profile: minimal
    - name: Install WebAssembly
      run: rustup target add wasm32-unknown-unknown
    - name: Install Trunk
      run: cargo install trunk
    - name: Build
      run: trunk build --public-url https://gonanf.github.io/ropa_prototipo/ --release
      
      
