name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check proyect
      uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            profile: minimal
    - name: Install WebAssembly
      run: rustup target add wasm32-unknown-unknown
    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install tailwindcss
      run: npm install -D tailwindcss
    - name: Init tailwindcss
      run: npx tailwindcss init
    - name: Install Trunk
      run: cargo install trunk
    - name: Build
      run: trunk build --public-url https://gonanf.github.io/ropa_prototipo/ --release
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
          path: "./dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      
      
